import os

EMBED_MODEL_NAME = os.getenv("EMBED_MODEL_NAME", "BAAI/bge-m3")
EMB_CACHE_DIR = os.getenv("EMB_CACHE_DIR", "emb_cache")

EMB_BATCH_SIZE = int(os.getenv("EMB_BATCH_SIZE", "4"))
EMB_MAX_SEQ_LEN = int(os.getenv("EMB_MAX_SEQ_LEN", "2048"))

LLM_MODEL = os.getenv("LLM_MODEL", "gpt-4o-mini")
LLM_BASE_URL = os.getenv("OPENAI_BASE_URL")
LLM_API_KEY = os.getenv("OPENAI_API_KEY")
OCCUPATIONS_PATH = os.getenv("OCCUPATIONS_PATH")
LLM_MAX_RETRIES, LLM_BASE_DELAY = 3, 2.0

W_FULL, W_TITLE = 0.6, 0.4
RRF_K = 60
MAX_CANDIDATES = 15
SCAN_DEPTH = 5

THRESHOLD_MATCH  = 0.50
THRESHOLD_SPARSE = 0.30
SECONDARY_MIN    = 0.50
SECONDARY_MARGIN = 0.01
PAIR_SIM_MAX     = 0.85

DISCOVERY_MATCH   = 0.60
DISCOVERY_FLOOR   = 0.35
DISCOVERY_RELATED = 3

NAMED_JOB_SPARSE = 0.40

PREVIEW_ITEMS = 5

SELECT_MAX_TOKENS = 300

PROFILE_TOP_N        = 5
PROFILE_W_DENSE      = 0.5
PROFILE_W_COVER      = 0.5
PROFILE_DENSE_ONLY   = 0.62
PROFILE_MIN_ITEMS    = 2
PROFILE_MIN_FIELDS   = 2
PROFILE_TOKEN_MIN    = 4

DENSE_LEAD_MARGIN = 0.03
DENSE_LEAD_DEPTH  = 5

TITLE_TIEBREAK_MARGIN = 0.05
TITLE_TIEBREAK_DEPTH  = 4
TITLE_TOKEN_MIN       = 4
