import os

EMBED_MODEL_NAME = os.getenv("EMBED_MODEL_NAME", "BAAI/bge-m3")
EMB_CACHE_DIR = os.getenv("EMB_CACHE_DIR", "emb_cache")

EMB_BATCH_SIZE = int(os.getenv("EMB_BATCH_SIZE", "4"))
EMB_MAX_SEQ_LEN = int(os.getenv("EMB_MAX_SEQ_LEN", "2048"))

LLM_MODEL = os.getenv("LLM_MODEL", "gpt-5.6-luna")
LLM_BASE_URL = os.getenv("OPENAI_BASE_URL")
LLM_API_KEY = os.getenv("OPENAI_API_KEY")
OCCUPATIONS_PATH = os.getenv("OCCUPATIONS_PATH")
LLM_MAX_RETRIES, LLM_BASE_DELAY = 3, 2.0

W_FULL, W_TITLE = 0.6, 0.4
RRF_K = 60
MAX_CANDIDATES = 15
SCAN_DEPTH = 5

THRESHOLD_MATCH  = 0.50
THRESHOLD_SPARSE = 0.30
SECONDARY_MIN    = 0.50
SECONDARY_MARGIN = 0.01
PAIR_SIM_MAX     = 0.85
PAIR_COVER_MARGIN = 0.07

DISCOVERY_FLOOR      = 0.35
DISCOVERY_CANDIDATES = 1
DISCOVERY_RELATED    = 1
DISCOVERY_MATCH      = 0.60

NAMED_JOB_SPARSE     = 0.40


PREVIEW_ITEMS = 5

SELECT_MAX_TOKENS = 300
RESOLVE_MAX_TOKENS = 1500
DRAFT_MAX_ITEMS = {"aliases": 4, "tools": 8, "skills": 8, "knowledge": 7, "abilities": 7,
                   "responsibilities": 9, "work_context": 7, "career_path_next": 4}
ADAPTED_MAX_TOKENS = 700

PROFILE_TOP_N        = 5
PROFILE_W_DENSE      = 0.5
PROFILE_W_COVER      = 0.5
PROFILE_DENSE_ONLY   = 0.62
PROFILE_DENSE_FLOOR  = 0.45
PROFILE_DENSE_CEIL   = 0.75
PROFILE_KNOWN_MIN    = 0.5
PROFILE_IDF_CAP      = 4.0
PROFILE_CONTEXT_ITEMS = 6
PROFILE_RECORD_MATCHES = 3
PROFILE_MAX_TOKENS = 2000
PROFILE_ELSEWHERE_WEIGHT = 0.6
PROFILE_WEIGHT_MIN   = 0.05
PROFILE_TOKEN_MIN    = 4
PROFILE_SHORT_MIN    = 2

DENSE_LEAD_MARGIN = 0.03
DENSE_LEAD_DEPTH  = 5

TITLE_TIEBREAK_MARGIN = 0.05
TITLE_TIEBREAK_DEPTH  = 4
TITLE_TOKEN_MIN       = 4
